/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClaimRegistrationRouteImport } from './routes/claim-registration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VictimsIndexRouteImport } from './routes/victims/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as ClaimsIndexRouteImport } from './routes/claims/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as VictimsVictimIdRouteImport } from './routes/victims/$victimId'
import { Route as ReportsVictimsRouteImport } from './routes/reports/victims'
import { Route as ReportsSettlementRouteImport } from './routes/reports/settlement'
import { Route as ReportsScamCompaniesRouteImport } from './routes/reports/scam-companies'
import { Route as ReportsPaymentsRouteImport } from './routes/reports/payments'
import { Route as ReportsEligibilityRouteImport } from './routes/reports/eligibility'
import { Route as ReportsAuditRouteImport } from './routes/reports/audit'
import { Route as FinanceMetricIdRouteImport } from './routes/finance/$metricId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims/$claimId'
import { Route as ClaimWindowsWindowIdRouteImport } from './routes/claim-windows/$windowId'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts/$alertId'
import { Route as CompaniesCompanyIdIndexRouteImport } from './routes/companies/$companyId/index'
import { Route as CompaniesCompanyIdSchemesSchemeIdRouteImport } from './routes/companies/$companyId/schemes/$schemeId'

const ClaimRegistrationRoute = ClaimRegistrationRouteImport.update({
  id: '/claim-registration',
  path: '/claim-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VictimsIndexRoute = VictimsIndexRouteImport.update({
  id: '/victims/',
  path: '/victims/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const VictimsVictimIdRoute = VictimsVictimIdRouteImport.update({
  id: '/victims/$victimId',
  path: '/victims/$victimId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVictimsRoute = ReportsVictimsRouteImport.update({
  id: '/reports/victims',
  path: '/reports/victims',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSettlementRoute = ReportsSettlementRouteImport.update({
  id: '/reports/settlement',
  path: '/reports/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsScamCompaniesRoute = ReportsScamCompaniesRouteImport.update({
  id: '/reports/scam-companies',
  path: '/reports/scam-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPaymentsRoute = ReportsPaymentsRouteImport.update({
  id: '/reports/payments',
  path: '/reports/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEligibilityRoute = ReportsEligibilityRouteImport.update({
  id: '/reports/eligibility',
  path: '/reports/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAuditRoute = ReportsAuditRouteImport.update({
  id: '/reports/audit',
  path: '/reports/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceMetricIdRoute = FinanceMetricIdRouteImport.update({
  id: '/finance/$metricId',
  path: '/finance/$metricId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimWindowsWindowIdRoute = ClaimWindowsWindowIdRouteImport.update({
  id: '/claim-windows/$windowId',
  path: '/claim-windows/$windowId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdIndexRoute = CompaniesCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesCompanyIdRoute,
} as any)
const CompaniesCompanyIdSchemesSchemeIdRoute =
  CompaniesCompanyIdSchemesSchemeIdRouteImport.update({
    id: '/schemes/$schemeId',
    path: '/schemes/$schemeId',
    getParentRoute: () => CompaniesCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim-registration': typeof ClaimRegistrationRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/claim-windows/$windowId': typeof ClaimWindowsWindowIdRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRouteWithChildren
  '/finance/$metricId': typeof FinanceMetricIdRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/eligibility': typeof ReportsEligibilityRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/scam-companies': typeof ReportsScamCompaniesRoute
  '/reports/settlement': typeof ReportsSettlementRoute
  '/reports/victims': typeof ReportsVictimsRoute
  '/victims/$victimId': typeof VictimsVictimIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/claims/': typeof ClaimsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/victims/': typeof VictimsIndexRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/schemes/$schemeId': typeof CompaniesCompanyIdSchemesSchemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim-registration': typeof ClaimRegistrationRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/claim-windows/$windowId': typeof ClaimWindowsWindowIdRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/finance/$metricId': typeof FinanceMetricIdRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/eligibility': typeof ReportsEligibilityRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/scam-companies': typeof ReportsScamCompaniesRoute
  '/reports/settlement': typeof ReportsSettlementRoute
  '/reports/victims': typeof ReportsVictimsRoute
  '/victims/$victimId': typeof VictimsVictimIdRoute
  '/assets': typeof AssetsIndexRoute
  '/claims': typeof ClaimsIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/victims': typeof VictimsIndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/schemes/$schemeId': typeof CompaniesCompanyIdSchemesSchemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim-registration': typeof ClaimRegistrationRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/claim-windows/$windowId': typeof ClaimWindowsWindowIdRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRouteWithChildren
  '/finance/$metricId': typeof FinanceMetricIdRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/eligibility': typeof ReportsEligibilityRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/scam-companies': typeof ReportsScamCompaniesRoute
  '/reports/settlement': typeof ReportsSettlementRoute
  '/reports/victims': typeof ReportsVictimsRoute
  '/victims/$victimId': typeof VictimsVictimIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/claims/': typeof ClaimsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/victims/': typeof VictimsIndexRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/schemes/$schemeId': typeof CompaniesCompanyIdSchemesSchemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim-registration'
    | '/alerts/$alertId'
    | '/claim-windows/$windowId'
    | '/claims/$claimId'
    | '/companies/$companyId'
    | '/finance/$metricId'
    | '/reports/audit'
    | '/reports/eligibility'
    | '/reports/payments'
    | '/reports/scam-companies'
    | '/reports/settlement'
    | '/reports/victims'
    | '/victims/$victimId'
    | '/assets/'
    | '/claims/'
    | '/companies/'
    | '/reports/'
    | '/victims/'
    | '/companies/$companyId/'
    | '/companies/$companyId/schemes/$schemeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim-registration'
    | '/alerts/$alertId'
    | '/claim-windows/$windowId'
    | '/claims/$claimId'
    | '/finance/$metricId'
    | '/reports/audit'
    | '/reports/eligibility'
    | '/reports/payments'
    | '/reports/scam-companies'
    | '/reports/settlement'
    | '/reports/victims'
    | '/victims/$victimId'
    | '/assets'
    | '/claims'
    | '/companies'
    | '/reports'
    | '/victims'
    | '/companies/$companyId'
    | '/companies/$companyId/schemes/$schemeId'
  id:
    | '__root__'
    | '/'
    | '/claim-registration'
    | '/alerts/$alertId'
    | '/claim-windows/$windowId'
    | '/claims/$claimId'
    | '/companies/$companyId'
    | '/finance/$metricId'
    | '/reports/audit'
    | '/reports/eligibility'
    | '/reports/payments'
    | '/reports/scam-companies'
    | '/reports/settlement'
    | '/reports/victims'
    | '/victims/$victimId'
    | '/assets/'
    | '/claims/'
    | '/companies/'
    | '/reports/'
    | '/victims/'
    | '/companies/$companyId/'
    | '/companies/$companyId/schemes/$schemeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRegistrationRoute: typeof ClaimRegistrationRoute
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  ClaimWindowsWindowIdRoute: typeof ClaimWindowsWindowIdRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRouteWithChildren
  FinanceMetricIdRoute: typeof FinanceMetricIdRoute
  ReportsAuditRoute: typeof ReportsAuditRoute
  ReportsEligibilityRoute: typeof ReportsEligibilityRoute
  ReportsPaymentsRoute: typeof ReportsPaymentsRoute
  ReportsScamCompaniesRoute: typeof ReportsScamCompaniesRoute
  ReportsSettlementRoute: typeof ReportsSettlementRoute
  ReportsVictimsRoute: typeof ReportsVictimsRoute
  VictimsVictimIdRoute: typeof VictimsVictimIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  VictimsIndexRoute: typeof VictimsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/claim-registration': {
      id: '/claim-registration'
      path: '/claim-registration'
      fullPath: '/claim-registration'
      preLoaderRoute: typeof ClaimRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/victims/': {
      id: '/victims/'
      path: '/victims'
      fullPath: '/victims/'
      preLoaderRoute: typeof VictimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/victims/$victimId': {
      id: '/victims/$victimId'
      path: '/victims/$victimId'
      fullPath: '/victims/$victimId'
      preLoaderRoute: typeof VictimsVictimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/victims': {
      id: '/reports/victims'
      path: '/reports/victims'
      fullPath: '/reports/victims'
      preLoaderRoute: typeof ReportsVictimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/settlement': {
      id: '/reports/settlement'
      path: '/reports/settlement'
      fullPath: '/reports/settlement'
      preLoaderRoute: typeof ReportsSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/scam-companies': {
      id: '/reports/scam-companies'
      path: '/reports/scam-companies'
      fullPath: '/reports/scam-companies'
      preLoaderRoute: typeof ReportsScamCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payments': {
      id: '/reports/payments'
      path: '/reports/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof ReportsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/eligibility': {
      id: '/reports/eligibility'
      path: '/reports/eligibility'
      fullPath: '/reports/eligibility'
      preLoaderRoute: typeof ReportsEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/audit': {
      id: '/reports/audit'
      path: '/reports/audit'
      fullPath: '/reports/audit'
      preLoaderRoute: typeof ReportsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/$metricId': {
      id: '/finance/$metricId'
      path: '/finance/$metricId'
      fullPath: '/finance/$metricId'
      preLoaderRoute: typeof FinanceMetricIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-windows/$windowId': {
      id: '/claim-windows/$windowId'
      path: '/claim-windows/$windowId'
      fullPath: '/claim-windows/$windowId'
      preLoaderRoute: typeof ClaimWindowsWindowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId/': {
      id: '/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof CompaniesCompanyIdIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRoute
    }
    '/companies/$companyId/schemes/$schemeId': {
      id: '/companies/$companyId/schemes/$schemeId'
      path: '/schemes/$schemeId'
      fullPath: '/companies/$companyId/schemes/$schemeId'
      preLoaderRoute: typeof CompaniesCompanyIdSchemesSchemeIdRouteImport
      parentRoute: typeof CompaniesCompanyIdRoute
    }
  }
}

interface CompaniesCompanyIdRouteChildren {
  CompaniesCompanyIdIndexRoute: typeof CompaniesCompanyIdIndexRoute
  CompaniesCompanyIdSchemesSchemeIdRoute: typeof CompaniesCompanyIdSchemesSchemeIdRoute
}

const CompaniesCompanyIdRouteChildren: CompaniesCompanyIdRouteChildren = {
  CompaniesCompanyIdIndexRoute: CompaniesCompanyIdIndexRoute,
  CompaniesCompanyIdSchemesSchemeIdRoute:
    CompaniesCompanyIdSchemesSchemeIdRoute,
}

const CompaniesCompanyIdRouteWithChildren =
  CompaniesCompanyIdRoute._addFileChildren(CompaniesCompanyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRegistrationRoute: ClaimRegistrationRoute,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  ClaimWindowsWindowIdRoute: ClaimWindowsWindowIdRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRouteWithChildren,
  FinanceMetricIdRoute: FinanceMetricIdRoute,
  ReportsAuditRoute: ReportsAuditRoute,
  ReportsEligibilityRoute: ReportsEligibilityRoute,
  ReportsPaymentsRoute: ReportsPaymentsRoute,
  ReportsScamCompaniesRoute: ReportsScamCompaniesRoute,
  ReportsSettlementRoute: ReportsSettlementRoute,
  ReportsVictimsRoute: ReportsVictimsRoute,
  VictimsVictimIdRoute: VictimsVictimIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  VictimsIndexRoute: VictimsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
